/**:
  ros__parameters:
    mission_type: 2
    rates:
      state_publishing: 50
      actuator_publishing: 40
      mission_info_publishing: 2

    # mission timeout: time for which the mission will be executed
    timeouts:
      mission_timeout: 30
    # actuator timeout: time in which the actuator values should be updated
      actuator_timeout: 1500000000
    # state timeout: time in which the state should be updated
      state_timeout: 0.1

    trims:
      thrust: 0.24
      rudder: 0.0

    max_input:
      thrust: 0.6
      rudder: 0.9

    glassy_simulation: false




      