
std_msgs/Header header


float64[] surge_drag_param_estimates
float64[] yawrate_drag_param_estimates

float64 gamma_dot
float64 gamma_dot_dot

float64 gamma_dot_err

float64 u_star
float64 r_star

float64 u
float64 r

float64 u_err
float64 r_err

float64 p_err_x_body
float64 p_err_y_body

float64 u_integral_contrib
float64 u_deriv_contrib
float64 u_proportional_contrib
float64 u_star_deriv_contrib
float64 other_u_contrib

float64 r_integral_contrib
float64 r_deriv_contrib
float64 r_proportional_contrib
float64 r_star_deriv_contrib
float64 other_r_contrib