glassy_joy_node:
  ros__parameters:
    mapping:
      thrust: [0,1]
      steering: [0,2]
      arm: [1, 0]
      disarm: [1, 2]
      start_offboard: [1,3]
      stop_offboard: [1,4]
      const_val_increase: [0,7]
      const_val_decrease: [0,7]
      step_increase: [0,6]
      step.decrease: [0,6]

      

