glassy_joy_node:
  ros__parameters:
    mapping:
      axes:
        thrust: 1
        steering: 2
      buttons:
        arm: 0
        disarm: 2
        start_offboard: 3
        stop_offboard: 4
      others:
        const_val_increase: [0,7]
        const_val_decrease: [0,7]
        step_increase: [0,6]
        step.decrease: [0,6]

      

