/**:
  ros__parameters:
    pid_gains:
      surge: [12.0, 10.0, 0.0]
      yaw: [15.0, 0.001, 1.2]
      yaw_rate: [10.0, 0.0, 0.0]
    rates:
      inner_loop: 40.0
    cancel_dynamics: true



    