/**:
  ros__parameters:
    glassy_pathgen:
      home_lat: 38.766040120113615 
      home_lon: -9.092953087610141
      path_defs:
        path_type: "dubins"
        r_min: 6.0
        online_gen: false
        rate: 2.0
        loop: true
        ignore_start_loop: true
        speed_arcs: 3.0
        speed_straight: 5.0
        speed: 3.0

      folder_circuits: "target_examples"
      circuit: "circuit_1.py"

      waypoints: 
        [
        0.0,0.0,  0.0 , 
        -24.0 ,0.0, 3.014159265,
        -30.0, -35.0 ,  0.0 ,
        0.0 , -30.0,-1.057079633,
        0.0, 0.0, 0.0
        ]